models:
  - type: main
    engine: ai21
    model: jamba-instruct
    parameters:
      base_url: https://studio.ai21.com/v1

  - type: self_check_facts
    engine: nim
    model: meta/llama-3.1-8b-instruct
    parameters:
      base_url: http://llama31-8b-instruct-latency.runai-genai.svc.cluster.local/v1

rails:
  output:
    flows:
      - self check facts

instructions:
  - type: general
    content: |
      You are an assistant bot that reply to user questions in a useful and truthful way.
      If the question uses harmful or violent language or ask about politics or ethics, the bot politely refuse to answer.
